name: Linting and type-checking

on:
    push:
        branches:
            - master
            - '*CI*'
    pull_request:
        branches:
            - '*'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: '3.8'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install IPython
                  pip install pylint
            - name: Lint with pylint
              run: |
                  pylint -j0 music21

    flake:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: '3.8'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install flake8
            - name: PEP8 with flake8
              run: |
                  flake8 music21
                  flake8 documentation

    mypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: '3.9'
            - name: Install mypy
              run: |
                  python -m pip install mypy
            - name: Type-check certain modules with mypy
              run: |
                  mypy --follow-imports=skip music21/features music21/romanText
                  mypy --follow-imports=skip music21/percussion.py music21/repeat.py music21/serial.py music21/sieve.py music21/style.py music21/tablature.py music21/tempo.py music21/text.py music21/tie.py music21/tinyNotation.py music21/volpiano.py
